# Generated by Django 4.0.6 on 2022-09-06 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
    ]
