# Generated by Django 4.0.6 on 2022-09-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dob',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
