# Generated by Django 4.1 on 2022-09-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_table'),
        ('clientes', '0004_alter_cliente_dob'),
    ]

    operations = [
    ]
