# Generated by Django 4.1 on 2022-09-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_merge_0002_alter_cliente_table_0004_alter_cliente_dob'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
