# Generated by Django 4.1 on 2022-09-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamos_tabla',
        ),
    ]
